name: List services in GCP
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'echo'
      name: 'echo values'
      run: |-
        echo ${GITHUB_ORG}
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2'
      with:
          project_id: 'gke07262023'
          create_credentials_file: true
          workload_identity_provider: 'projects/57038048924/locations/global/workloadIdentityPools/github/providers/ghactionscourse'
          service_account: 'github-actions-svc-account@gke07262023.iam.gserviceaccount.com'
         
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud services list
        echo  ${{ steps.auth.outputs.access_token }}
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
