name: List services in GCP
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: ${{ secrets.your-checkout-token }}
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'https://github.com/github'
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'echo'
      name: 'echo values'
      run: |-
        echo ${GITHUB_ORG}
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2'
      with:
          token_format: 'access_token'
          project_id: 'gke07262023'
          create_credentials_file: true
          workload_identity_provider: 'projects/gke07262023/locations/global/workloadIdentityPools/github/providers/ghactionscourse'
          service_account: 'github-actions-svc-account@gke07262023.iam.gserviceaccount.com'
         
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        echo  ${{ steps.auth.outputs.access_token }}
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
