name: List services in GCP
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'echo'
      name: 'echo values'
      run: |-
        echo ${GITHUB_ORG}
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2'
      with:
          create_credentials_file: true
          workload_identity_provider: 'projects/gke07262023/locations/global/workloadIdentityPools/actions/providers/my-repo'
          service_account: 'github-actions-svc-account@gke07262023.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
      
        gcloud services list
