name: Matrix
on: [push]

# Original Configuration
# {os: ubuntu-latest, node-version: 14} X Excludes will remove this
# {os: ubuntu-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 16}
# {os: windows-latest, node-version: 14}
# {os: windows-latest, node-version: 15}
# {os: windows-latest, node-version: 16}
# {os: macos-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 17}

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        include:
          - os: ubuntu-latest # gets added to all ubuntu combos
            is-ubuntu: true
          - os: macos-latest
            node-version: 15
          - experimental: false # gets added to all keys
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-latest
            node-version: 14
      fail-fast: false
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v