name: Status Check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run:  Sleep 20
            - name: Runs on Failure
              if: failure()
              run: echo "Job Failed"
            - name: Runs on Success
              if: success() # not needed (DEFAULT BEHAVIOR)
              run: echo "Runs on Success"
            - name: Always Runs
              if: always() # if success() || failure()
              run: echo "Always Runs"
            - name: Runs on Cancel
              if: cancelled()
              run: echo "Runs on Cancel"
              
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - name: Checkout
              run: echo 'Job 2'