name: Calling reusable Workflows
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name of the workflow to run'
                required: true
                default: 'David calling from $$ {{ github.event.inputs.name }} $$'
                type: string
jobs:
    calling-a-reusable-workflow:
        uses: dapolloxp/reuseable/.github/workflows/reusable.yaml@main
        with:
            name: ${{ github.event.inputs.name }}
        secrets: # inherit secrets from the calling workflow
            access-token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reusable-workflow-in-same-repo:
        uses: ./.github/workflows/reusable-workflow.yaml
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-workflow-in-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reusable-workflow-in-same-repo.outputs.date }}
