name: Variables and Secrets
on: [push]

jobs:
    decrypt-file:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Decrypt file
          env:
            PASSPHRASE: ${{ secrets.PASSPHRASE }}
          run: |
            mkdir $HOME/secrets
            gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output 
            $HOME/secrets/secret.json encrypted/file.json.gpg
        - name: Read the file
          run: |
            cat $HOME/secrets/secret.json
    log-vars:
      runs-on: ${{ vars.RUNNER }}
      environment: "staging"
      env:
        BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
        ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
        REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        #ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      steps:
        - name: testing Boolean secret
          run: |
            echo "BOOLEAN_SECRET: $BOOLEAN_SECRET"
        - name: Run only if BOOLEAN_SECRET is true
          if: env.BOOLEAN_SECRET == 'true'
          run: |
            echo "This step runs only if BOOLEAN_SECRET is true"
            echo "I ran, I ran so far away"

          
        - name: Log all the variables
          run: |
            echo '${{ vars.RUNNER}}'
            echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
            echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
        

      