name: Variables and Secrets
on: [push]

jobs:
    log-vars:
      runs-on: ${{ vars.RUNNER }}
      env:
        BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
        ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
        REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        #ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      steps:
        - name: Run only if BOOLEAN_SECRET is true
          if: ${{ env.BOOLEAN_SECRET == 'true' }}
          run: echo "This step runs only if BOOLEAN_SECRET is true"
          run: echo "I ran"
        - name: Log all the variables
          run: |
            echo '${{ vars.RUNNER}}'
            echo "REPO_LEVEL_VAR: $ENV_LEVEL_VAR"
            echo "ENV_LEVEL_VAR: $REPO_LEVEL_VAR"
        

      