name: Working Dirs & Shells
on: [push]
jobs:
    display-wd-info:
       runs-on: ubuntu-latest
       steps:
        - name: Display Working Directory & List Files
          run: |
            pwd
            ls -la
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo $GITHUB_ACTION
    display-wd-info:
        runs-on: windows-latest
        steps:
            - name: Display Working Directory & List Files
            run: |
                pwd
                ls -la
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                echo $GITHUB_ACTION