name: Workflow Commands
on: [push]

jobs:
    testing-wd-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting a error message with parameters
              run: echo "::error title=Error Title,file=app.js,line=2,endLine=3, col=5,endColumn=7::Missing semicolon"
            - name: Setting a debug message with parameters
              run: echo "::debug title=Debug Title,file=app.js,line=2,endLine=3, col=5,endColumn=7::Missing semicolon"
            - name: Setting a warning message with parameters
              run: echo "::warning title=Warning Title,file=app.js,line=2,endLine=3, col=5,endColumn=7::Missing semicolon"
            - name: Setting a notice message with parameters
              run: echo "::notice title=Notice Title,file=app.js,line=2,endLine=3, col=5,endColumn=7::Missing semicolon"